resources:
  - ../base
nameSuffix: -tenant-two
configMapGenerator:
  - name: mt-app-config
    behavior: replace
    literals:
      - TENANT_ID=TNT02

replacements:
  - source:
      kind: Deployment
      fieldPath: metadata.name
    targets:
      - select:
          kind: Deployment
        fieldPaths:
          - spec.selector.matchLabels.app
          - spec.template.metadata.labels.app
      - select:
          kind: Service
        fieldPaths:
          - spec.selector.app